#!/usr/bin/env node
/**
 * 回填 authors / tags / book_tags 三张 SEO 元数据表。
 *
 * 用法：
 *   node scripts/backfill_seo_meta.mjs --local     # 本地 D1
 *   node scripts/backfill_seo_meta.mjs --remote    # 远端 D1（需 CLOUDFLARE_API_TOKEN）
 *   node scripts/backfill_seo_meta.mjs --dry-run   # 只生成 SQL，不执行
 *
 * 数据流：
 *   books.author -> authors(name, book_count)
 *   books.keywords_json -> book_tags(book_id, tag_name) -> tags(name, book_count)
 *
 * 依赖前置：
 *   - 已经应用 db/migrations/0002_seo_meta.sql
 *   - books.keywords_json 已被 seo:keyword-backfill 填充
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");
const outputDir = path.join(projectRoot, "db", "seed");
const outputFile = path.join(outputDir, "seo_meta_backfill.sql");

function parseArgs(argv) {
  const args = { local: false, remote: false, dryRun: false };
  for (const arg of argv) {
    if (arg === "--local") args.local = true;
    else if (arg === "--remote") args.remote = true;
    else if (arg === "--dry-run") args.dryRun = true;
    else throw new Error(`Unknown argument: ${arg}`);
  }
  if (!args.dryRun && args.remote === args.local) {
    throw new Error("Choose exactly one target: --local, --remote, or --dry-run.");
  }
  return args;
}

function buildBackfillSql() {
  return [
    "-- Auto-generated by scripts/backfill_seo_meta.mjs",
    "-- 回填 authors / tags / book_tags。运行前请确保 0002_seo_meta.sql 已应用。",
    "",
    "BEGIN TRANSACTION;",
    "",
    "-- 1) authors：按 books.author 聚合",
    "INSERT OR IGNORE INTO authors (name, book_count, updated_at)",
    "SELECT",
    "  TRIM(author) AS name,",
    "  COUNT(*) AS book_count,",
    "  datetime('now') AS updated_at",
    "FROM books",
    "WHERE TRIM(author) != ''",
    "GROUP BY TRIM(author);",
    "",
    "-- 2) book_tags：从 keywords_json 拆分",
    "INSERT OR IGNORE INTO book_tags (book_id, tag_name)",
    "SELECT",
    "  b.id AS book_id,",
    "  TRIM(CAST(j.value AS TEXT)) AS tag_name",
    "FROM books b,",
    "  json_each(CASE WHEN json_valid(b.keywords_json) THEN b.keywords_json ELSE '[]' END) j",
    "WHERE TRIM(CAST(j.value AS TEXT)) != '';",
    "",
    "-- 3) tags：按 book_tags 聚合",
    "INSERT OR IGNORE INTO tags (name, book_count, updated_at)",
    "SELECT",
    "  tag_name AS name,",
    "  COUNT(DISTINCT book_id) AS book_count,",
    "  datetime('now') AS updated_at",
    "FROM book_tags",
    "GROUP BY tag_name;",
    "",
    "COMMIT;",
    "",
  ].join("\n");
}

function runWranglerD1(args, sqlFile) {
  return new Promise((resolve, reject) => {
    const child = spawn("npx", ["wrangler", "d1", "execute", "qifeibook", ...args, "--file", sqlFile], {
      cwd: projectRoot,
      stdio: "inherit",
      env: process.env,
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`wrangler d1 execute exited with code ${code}`));
    });
  });
}

const args = parseArgs(process.argv.slice(2));
const sql = buildBackfillSql();
await mkdir(outputDir, { recursive: true });
await writeFile(outputFile, sql, "utf8");
console.log(`Wrote ${outputFile}`);

if (args.dryRun) {
  console.log("--dry-run: SQL file generated. Review then apply with --local or --remote.");
} else if (args.local) {
  console.log("Applying to local D1...");
  await runWranglerD1(["--local"], outputFile);
  console.log("Local D1 backfill complete.");
} else if (args.remote) {
  console.log("Applying to remote D1...");
  await runWranglerD1(["--remote"], outputFile);
  console.log("Remote D1 backfill complete.");
}