import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { deriveBookKeywords } from "./seo_keywords.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");
const sourceFile = path.join(projectRoot, "data", "mockData.ts");
const outputDir = path.join(projectRoot, "db", "seed");
const outputFile = path.join(outputDir, "books.sql");
const remoteOutputFile = path.join(outputDir, "books.remote.sql");

function escapeSqlValue(value) {
  if (value === null || value === undefined || value === "") {
    return "NULL";
  }

  return `'${String(value).replaceAll("'", "''")}'`;
}

function toSqlInteger(value) {
  return Number.isFinite(value) ? String(value) : "NULL";
}

function normalizeTextValue(value) {
  if (value === null || value === undefined) {
    return "";
  }

  return String(value).trim();
}

function requireTextValue(value, fieldName, bookId) {
  const normalizedValue = normalizeTextValue(value);

  if (!normalizedValue) {
    throw new Error(`Book ${bookId} is missing required field: ${fieldName}`);
  }

  return normalizedValue;
}

function getAuthorValue(value) {
  return normalizeTextValue(value) || "未知作者";
}

function extractBooksArray(sourceText) {
  const marker = "export const books: Book[] =";
  const markerIndex = sourceText.indexOf(marker);

  if (markerIndex === -1) {
    throw new Error("Unable to locate exported books array in data/mockData.ts");
  }

  const arrayStart = sourceText.indexOf("[", markerIndex);
  const arrayEnd = sourceText.lastIndexOf("];");

  if (arrayStart === -1 || arrayEnd === -1) {
    throw new Error("Unable to extract books array literal from data/mockData.ts");
  }

  const arrayLiteral = sourceText.slice(arrayStart, arrayEnd + 1);
  return Function(`"use strict"; return (${arrayLiteral});`)();
}

function buildCategoryRows(bookList) {
  const counts = new Map();

  for (const book of bookList) {
    const categoryName = requireTextValue(book.category, "category", book.id);
    counts.set(categoryName, (counts.get(categoryName) ?? 0) + 1);
  }

  return [...counts.entries()]
    .sort((left, right) => left[0].localeCompare(right[0], "zh-CN"))
    .map(([name, bookCount], index) => ({
      id: index + 1,
      name,
      slug: name,
      bookCount,
    }));
}

function assertUniqueBookIds(bookList) {
  const seenIds = new Map();
  const duplicateEntries = [];

  for (const book of bookList) {
    const previousTitle = seenIds.get(book.id);

    if (previousTitle) {
      duplicateEntries.push(`${book.id}: ${previousTitle} / ${book.title}`);
      continue;
    }

    seenIds.set(book.id, book.title);
  }

  if (duplicateEntries.length > 0) {
    throw new Error(`Duplicate book ids detected: ${duplicateEntries.join("; ")}`);
  }
}

function buildSql(bookList, { includeTransaction = true } = {}) {
  const timestamp = new Date().toISOString();
  const categories = buildCategoryRows(bookList);
  const categoryIdByName = new Map(categories.map((category) => [category.name, category.id]));

  const lines = [
    "-- Auto-generated by scripts/export_books_to_sql.mjs",
    "-- Do not edit manually.",
  ];

  if (includeTransaction) {
    lines.push("BEGIN TRANSACTION;");
  }

  lines.push("DELETE FROM download_links;");
  lines.push("DELETE FROM books;");
  lines.push("DELETE FROM categories;");
  lines.push("INSERT INTO books_fts(books_fts) VALUES('delete-all');");
  lines.push("");

  for (const category of categories) {
    lines.push(
      `INSERT INTO categories (id, slug, name, book_count) VALUES (${toSqlInteger(category.id)}, ${escapeSqlValue(category.slug)}, ${escapeSqlValue(category.name)}, ${toSqlInteger(category.bookCount)});`,
    );
  }

  lines.push("");

  let downloadLinkId = 1;
  let skippedDownloadLinks = 0;

  for (const book of bookList) {
    const title = requireTextValue(book.title, "title", book.id);
    const author = getAuthorValue(book.author);
    const authorDetail = normalizeTextValue(book.authorDetail);
    const description = normalizeTextValue(book.description);
    const cover = normalizeTextValue(book.cover);
    const year = normalizeTextValue(book.year);
    const publishYear = normalizeTextValue(book.publishYear);
    const format = normalizeTextValue(book.format);
    const size = normalizeTextValue(book.size);
    const categoryName = requireTextValue(book.category, "category", book.id);
    const categoryId = categoryIdByName.get(categoryName);
    const keywords = deriveBookKeywords(book);
    const keywordsJson = JSON.stringify(keywords);

    lines.push(
      `INSERT INTO books (id, slug, title, author, author_detail, description, cover, year, publish_year, format, size, category_id, keywords_json, created_at, updated_at) VALUES (${toSqlInteger(book.id)}, NULL, ${escapeSqlValue(title)}, ${escapeSqlValue(author)}, ${escapeSqlValue(authorDetail)}, ${escapeSqlValue(description)}, ${escapeSqlValue(cover)}, ${escapeSqlValue(year)}, ${escapeSqlValue(publishYear)}, ${escapeSqlValue(format)}, ${escapeSqlValue(size)}, ${toSqlInteger(categoryId)}, ${escapeSqlValue(keywordsJson)}, ${escapeSqlValue(timestamp)}, ${escapeSqlValue(timestamp)});`,
    );

    for (const link of book.downloadLinks) {
      const linkName = normalizeTextValue(link.name) || "下载链接";
      const linkUrl = normalizeTextValue(link.url);

      if (!linkUrl) {
        skippedDownloadLinks += 1;
        continue;
      }

      const provider = linkName.includes("夸克") ? "quark" : linkName.includes("百度") ? "baidu" : "other";
      lines.push(
        `INSERT INTO download_links (id, book_id, provider, name, url, code) VALUES (${toSqlInteger(downloadLinkId)}, ${toSqlInteger(book.id)}, ${escapeSqlValue(provider)}, ${escapeSqlValue(linkName)}, ${escapeSqlValue(linkUrl)}, ${escapeSqlValue(link.code)});`,
      );
      downloadLinkId += 1;
    }

    const searchKeywords = keywords.join(" ");
    lines.push(
      `INSERT INTO books_fts (rowid, title, author, description, keywords) VALUES (${toSqlInteger(book.id)}, ${escapeSqlValue(title)}, ${escapeSqlValue(author)}, ${escapeSqlValue(description)}, ${escapeSqlValue(searchKeywords)});`,
    );
  }

  lines.push("");

  if (includeTransaction) {
    lines.push("COMMIT;");
    lines.push("");
  }

  return {
    sql: lines.join("\n"),
    categories: categories.length,
    books: bookList.length,
    downloadLinks: downloadLinkId - 1,
    skippedDownloadLinks,
  };
}

const sourceText = await readFile(sourceFile, "utf8");
const bookList = extractBooksArray(sourceText);
assertUniqueBookIds(bookList);
const localBuild = buildSql(bookList, { includeTransaction: true });
const remoteBuild = buildSql(bookList, { includeTransaction: false });

await mkdir(outputDir, { recursive: true });
await Promise.all([
  writeFile(outputFile, localBuild.sql, "utf8"),
  writeFile(remoteOutputFile, remoteBuild.sql, "utf8"),
]);

console.log(
  JSON.stringify(
    {
      outputFile,
      remoteOutputFile,
      categories: localBuild.categories,
      books: localBuild.books,
      downloadLinks: localBuild.downloadLinks,
      skippedDownloadLinks: localBuild.skippedDownloadLinks,
    },
    null,
    2,
  ),
);
