import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { deriveBookKeywords, summarizeKeywordCoverage } from "./seo_keywords.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDir, "..");
const sourceFile = path.join(projectRoot, "data", "mockData.ts");
const outputDir = path.join(projectRoot, "db", "seed");
const outputFile = path.join(outputDir, "keywords_backfill.sql");
const remoteOutputFile = path.join(outputDir, "keywords_backfill.remote.sql");

function escapeSqlValue(value) {
  if (value === null || value === undefined || value === "") {
    return "NULL";
  }

  return `'${String(value).replaceAll("'", "''")}'`;
}

function extractBooksArray(sourceText) {
  const marker = "export const books: Book[] =";
  const markerIndex = sourceText.indexOf(marker);

  if (markerIndex === -1) {
    throw new Error("Unable to locate exported books array in data/mockData.ts");
  }

  const arrayStart = sourceText.indexOf("[", markerIndex);
  const arrayEnd = sourceText.lastIndexOf("];");

  if (arrayStart === -1 || arrayEnd === -1) {
    throw new Error("Unable to extract books array literal from data/mockData.ts");
  }

  const arrayLiteral = sourceText.slice(arrayStart, arrayEnd + 1);
  return Function(`"use strict"; return (${arrayLiteral});`)();
}

function buildBackfillSql(bookList, { includeTransaction = true } = {}) {
  const lines = [
    "-- Auto-generated by scripts/generate_keyword_backfill_sql.mjs",
    "-- Only fills books with empty keywords_json; review before applying to remote D1.",
  ];

  if (includeTransaction) {
    lines.push("BEGIN TRANSACTION;");
  }

  let updateCount = 0;

  for (const book of bookList) {
    const keywords = deriveBookKeywords(book);

    if (keywords.length === 0) {
      continue;
    }

    lines.push(
      `UPDATE books SET keywords_json = ${escapeSqlValue(JSON.stringify(keywords))} WHERE id = ${Number(book.id)} AND (keywords_json IS NULL OR keywords_json = '' OR keywords_json = '[]');`,
    );
    updateCount += 1;
  }

  if (includeTransaction) {
    lines.push("COMMIT;");
  }

  lines.push("");

  return {
    sql: lines.join("\n"),
    updateCount,
  };
}

const sourceText = await readFile(sourceFile, "utf8");
const bookList = extractBooksArray(sourceText);
const localBuild = buildBackfillSql(bookList, { includeTransaction: true });
const remoteBuild = buildBackfillSql(bookList, { includeTransaction: false });
const coverage = summarizeKeywordCoverage(bookList);

await mkdir(outputDir, { recursive: true });
await Promise.all([writeFile(outputFile, localBuild.sql, "utf8"), writeFile(remoteOutputFile, remoteBuild.sql, "utf8")]);

console.log(
  JSON.stringify(
    {
      outputFile,
      remoteOutputFile,
      candidateUpdates: localBuild.updateCount,
      ...coverage,
    },
    null,
    2,
  ),
);
